pygments: true
server: true
server_port: 3000
auto: true
permalink: ./:title.html
img: images/global/header-logo.png
site_main: /
branding_url: branding_index.html
paginate: 2



basic_user_videos:
   - title: this is a title
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 2
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 3
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.
     
   - title: this is a title 4
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 2
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 3
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.
     
   - title: this is a title 4
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

group_admin_videos:
   - title: this is a title
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 2
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 3
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.
     
   - title: this is a title 4
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 2
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.

   - title: this is a title 3
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.
     
   - title: this is a title 4
     thumbnail: http://placehold.it/100x75
     description: this is a video about how to do things on the site.
